# Autogenerated wrapper script for Gingko_jll for aarch64-apple-darwin
export libgingko, libgingko_cuda, libgingko_device, libgingko_dpcpp, libgingko_hip, libgingko_omp, libgingko_reference

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Gingko")
JLLWrappers.@declare_library_product(libgingko, "@rpath/libginkgo.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_cuda, "@rpath/libginkgo_cuda.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_device, "@rpath/libginkgo_device.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_dpcpp, "@rpath/libginkgo_dpcpp.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_hip, "@rpath/libginkgo_hip.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_omp, "@rpath/libginkgo_omp.1.4.0.dylib")
JLLWrappers.@declare_library_product(libgingko_reference, "@rpath/libginkgo_reference.1.4.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgingko,
        "lib/libginkgo.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_cuda,
        "lib/libginkgo_cuda.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_device,
        "lib/libginkgo_device.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_dpcpp,
        "lib/libginkgo_dpcpp.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_hip,
        "lib/libginkgo_hip.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_omp,
        "lib/libginkgo_omp.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgingko_reference,
        "lib/libginkgo_reference.1.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
